<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.xserein666</groupId>
        <artifactId>jewel-a2a</artifactId>
        <version>1.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jewel-a2a-repository</artifactId>
    <packaging>jar</packaging>
    <name>Jewel-A2A Repository</name>

    <dependencies>
        <dependency>
            <groupId>io.github.xserein666</groupId>
            <artifactId>jewel-a2a-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>